name: Build and Upload Artifacts

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: macos-latest-xlarge
          - os: ubuntu-latest
            container: "paritytech/ci-unified:bullseye-1.74.0-2023-11-01-v20231204"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Free Disk Space (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v3

      # Install required packets
      - name: Install ninja
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt-get -y install ninja-build

      - name: Install ninja
        if: matrix.os == 'macos-latest-xlarge'
        run: |
          brew install ninja

      # Clone things
      - name: Download Necessary sources
        run: ./clone.sh

      # Patch things
      - name: Apply patches
        run: ./patch.sh

      # Build Dists
      - name: Build dist
        run: ./build_dist.sh

      # Push in the Github environment variable the name of the artifact
      # Doing this now because in the following step the rust folder will be delated to save some space before installing the toolchain
      - run: ./config.sh -artifact_name

      # Build Toolchain
      - name: Build Toolchain
        run: ./build_toolchain.sh
