name: Build and Upload Artifacts

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12-xl]

    steps:
      - uses: actions/checkout@v4

      - name: Install ninja
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt-get -y install ninja-build

      - name: Install ninja
        if: matrix.os == 'macos-12-xl'
        run: |
          brew install ninja

      - name: Download source
        run: ./clone.sh

      - name: Apply patches
        run: ./patch.sh

      - name: Build
        run: ./build.sh

      # Push in the Github environment variable the name of the artifact
      # Doing this now because in the following step the rust folder will
      # be delated to save some space before installing the toolchain
      - run: ./config.sh -artifact_name

      - name: Build Toolchain
        run: ./package.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: "${{ env.ARTIFACT_NAME }}.tar.zst"
