name: Build and upload artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest-xlarge]

    steps:
      - name: Free Disk Space (Ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: Install ninja
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt-get -y install ninja-build

      - name: Install ninja
        if: contains(matrix.os, 'macos')
        run: |
          brew install ninja

      - name: Download source
        run: ./clone.sh

      - name: Apply patches
        run: ./patch.sh

      - name: Build toolchain
        run: ./build.sh

      # Push in the Github environment variable the name of the artifact
      # Doing this now because in the following step the rust folder will
      # be delated to save some space before installing the toolchain
      - run: ./config.sh -artifact_name

      - name: Package toolchain
        run: ./package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: "${{ env.ARTIFACT_NAME }}.tar.zst"
